Repository TEAM-DoDream/DoDream_FE, pull requests merged in 2025-05, with the labels that each got.

#20 [✨FEATURE] 헤더 구현
  .coderabbit.yaml
  src/assets/icons/shortDivider.svg
  src/common/Footer.tsx
  src/common/Header.tsx
  src/outlet/.keep
  src/outlet/HideLayout.tsx
  src/outlet/ShowLayout.tsx
  src/pages/home/Home.tsx
  src/pages/login/components/Login.tsx
  src/pages/signup/components/Signup.tsx
  src/pages/signup/components/Signup2.tsx
  src/route/Router.tsx
Labels: 💄Style

#23 [✨FEATURE] 온보딩 페이지 UI 제작
  .coderabbit.yaml
  src/assets/icons/check.svg
  src/assets/images/onboarding.png
  src/common/Header.tsx
  src/hook/useOnboarding.ts
  src/pages/onboard/OnBoardingPage.tsx
  src/pages/onboard/components/Navigation.tsx
  src/pages/onboard/components/OptionSelector.tsx
  src/pages/onboard/components/Questions.tsx
  src/pages/onboard/components/Step.tsx
  src/pages/onboard/components/Stepper.tsx
  src/route/Router.tsx
  src/utils/.keep
  src/utils/data/onboard/onboardDummy.ts
Labels: ✨Feature, 💄Style

#29 [✨FEATURE] 로그인 유효성 검사
  package.json
  src/pages/login/LoginPage.tsx
  src/pages/login/components/Login.tsx
  src/pages/login/components/LoginForm.tsx
  src/pages/login/components/LoginImage.tsx
  src/validation/login/loginSchema.ts
  tailwind.config.js
  tsconfig.app.json
  tsconfig.json
  vercel.json
  yarn.lock
Labels: ✨Feature

#32 [✨FEATURE] 회원가입 validation 추가
  src/common/Input.tsx
  src/pages/signup/components/AddressInput.tsx
  src/pages/signup/components/AddressModal.tsx
  src/pages/signup/components/Signup.tsx
  src/pages/signup/components/Signup2.tsx
  src/validation/signup/SignupSchema.ts
Labels: ✨Feature

#38 [✨FEATURE] 온보딩 결과(직업추천) UI 제작
  src/assets/icons/lightbulb.svg
  src/assets/images/tmp.png
  src/pages/jobRecommend/JobRecommendPage.tsx
  src/pages/jobRecommend/components/Card.tsx
  src/pages/jobRecommend/components/JobTitle.tsx
  src/pages/onboard/OnBoardingPage.tsx
  src/pages/onboard/components/Navigation.tsx
  src/route/Router.tsx
  src/utils/data/jobRecommend/jobCardDummy.ts
Labels: ✨Feature, 💄Style

#41 [✨FEATURE] Jest + Testing Library를 이용한 테스트 환경 설정
  __mocks__/fileMock.js
  __mocks__/svgMock.tsx
  jest.config.ts
  jest.setup.ts
  package.json
  src/common/__tests__/Button.test.tsx
  src/common/__tests__/Input.test.tsx
  src/pages/jobRecommend/components/Card.tsx
  src/pages/jobRecommend/components/__tests__/Card.test.tsx
  src/pages/login/components/LoginForm.tsx
  src/type/login/mutation.ts
  tsconfig.json
  yarn.lock
Labels: 🐛Bug, ✨Feature, ⚒️Setting

#44 [✨FEATURE] 홈화면 UI 구현
  src/assets/icons/arrow.svg
  src/assets/icons/bell.svg
  src/assets/icons/like.svg
  src/assets/icons/myDreamarrow.svg
  src/assets/icons/purpleeye.svg
  src/assets/images/checker.png
  src/assets/images/home.png
  src/assets/images/home_card.png
  src/common/CheckList.tsx
  src/common/Header.tsx
  src/pages/home/Home.tsx
  src/pages/home/components/Banner.tsx
  src/pages/home/components/DreamerCard.tsx
  src/pages/home/components/HomeDreamer.tsx
  src/pages/home/components/HomeImage.tsx
  src/pages/home/components/HomeRecruit.tsx
  src/pages/home/components/LoginBanner.tsx
  src/pages/home/components/tab/ChallengeTab.tsx
  src/pages/home/components/tab/ReadyTab.tsx
  src/pages/home/components/tab/StartTab.tsx
  src/pages/signup/components/Signup.tsx
  src/utils/data/home/DreamerDummy.ts
  src/utils/data/home/RecruitDummy.ts
Labels: ✨Feature, 💄Style

#52 [✨FEATURE] 플로팅 UI 구현
  src/assets/icons/pencil.svg
  src/common/FloatingButton.tsx
  src/common/modal/FloatingModal.tsx
  src/outlet/ShowLayout.tsx
  src/pages/home/components/Banner.tsx
  src/pages/home/components/DreamerCard.tsx
  src/pages/home/components/HomeRecruit.tsx
  src/pages/home/components/LoginBanner.tsx
  src/pages/jobRecommend/components/JobTitle.tsx
  tailwind.config.js
Labels: ✨Feature, 💄Style

#55 [✨FEATURE] 일자리/배움터 찾기 UI 제작
  .coderabbit.yaml
  src/assets/icons/back.svg
  src/assets/icons/drop_down.svg
  src/assets/icons/refresh_icon.svg
  src/assets/icons/search.svg
  src/assets/images/lightbulb.png
  src/assets/images/reading.png
  src/common/DateInput.tsx
  src/common/DropDown.tsx
  src/common/Header.tsx
  src/common/RecruitCard.tsx
  src/common/ResetButton.tsx
  src/hook/useDropdown.ts
  src/pages/jobSearch/JobSearchPage.tsx
  src/pages/jobSearch/components/Filter.tsx
  src/route/Router.tsx
  src/store/filterStore.ts
  src/utils/data/search/searchDummy.ts
Labels: ✨Feature, 💄Style

#58 [✨FEATURE] 배움터 찾기 UI 제작
  src/assets/icons/cross.svg
  src/assets/images/illustration_1.webp
  src/assets/images/illustration_2.webp
  src/assets/images/job_search.webp
  src/assets/images/learn.webp
  src/assets/images/lightbulb.webp
  src/assets/images/writing.png
  src/common/DropDown.tsx
  src/common/Header.tsx
  src/pages/jobSearch/JobSearchPage.tsx
  src/pages/learning/LearningPage.tsx
  src/pages/learning/components/CardDetail.tsx
  src/pages/learning/components/Filter.tsx
  src/pages/learning/components/LearningCard.tsx
  src/route/Router.tsx
  src/store/filterStore.ts
  src/utils/data/learn/learnDummy.ts
Labels: ✨Feature, 💄Style

#61 [✨FEATURE] 직업탐색 UI 구현
  src/assets/icons/plus.svg
  src/assets/icons/purplecancel.svg
  src/assets/images/bag.webp
  src/assets/images/checker.png
  src/assets/images/foundillust.webp
  src/assets/images/heart.webp
  src/common/Header.tsx
  src/common/Pagination.tsx
  src/common/modal/AddJobModal.tsx
  src/hook/usePagination.ts
  src/pages/jobfound/JobFound.tsx
  src/pages/jobfound/components/FoundFilter.tsx
  src/pages/jobfound/components/ListFound.tsx
  src/route/Router.tsx
  src/store/filterStore.ts
  src/utils/data/jobfound/JobFoundDummy.ts
Labels: ✨Feature, 💄Style

#63 [🐛BUG] 아이콘 크기 에러 수정
  src/assets/icons/bell.svg
  src/assets/icons/lightbulb.svg
  src/assets/images/bell.webp
  src/assets/images/lightbulb.png
  src/pages/home/components/Banner.tsx
  src/pages/home/components/LoginBanner.tsx
  src/pages/jobRecommend/components/JobTitle.tsx
Labels: 🐛Bug, 💄Style

#66 [✨FEATURE] 온보딩 API 연결
  package.json
  src/common/LoadingSpinner.tsx
  src/hook/useOnboardMutation.ts
  src/hook/useOnboarding.ts
  src/pages/jobRecommend/JobRecommendPage.tsx
  src/pages/jobRecommend/components/Card.tsx
  src/pages/onboard/OnBoardingPage.tsx
  src/validation/jobRecommend/jobDataSchema.ts
  tailwind.config.js
  yarn.lock
Labels: ✨Feature

#69 [✨FEATURE] 직업 정보 페이지 UI 구현
  src/assets/icons/info.svg
  src/assets/icons/mobileLogo.svg
  src/assets/images/clap.webp
  src/assets/images/warning.webp
  src/common/Header.tsx
  src/pages/jobDetail/JobInfo.tsx
  src/pages/jobDetail/components/DetailSideBar.tsx
  src/pages/jobDetail/components/JobView.tsx
  src/pages/jobDetail/components/NoDataSideBar.tsx
  src/route/Router.tsx
  src/utils/data/home/RecruitDummy.ts
Labels: ✨Feature, 💄Style

#76 main 최신화
  src/hook/useRecruitListQuery.ts
Labels: 🐛Bug

#83 [🐛BUG] 일자리 찾기 로직 수정
  src/assets/icons/like.svg
  src/common/RecruitCard.tsx
  src/hook/useRecruitDetailQuery.ts
  src/pages/jobSearch/JobSearchPage.tsx
  src/pages/jobSearch/components/CardDetail.tsx
  src/pages/jobSearch/components/Filter.tsx
  src/pages/learning/components/Filter.tsx
  src/store/filterStore.ts
  src/store/learningFilterStore.ts
  src/utils/data/job/filterOptions.ts
  src/utils/data/job/jobMapper.ts
Labels: 🐛Bug

#87 [✨FEATURE] 홈 API 연결
  src/assets/icons/fullheart.svg
  src/assets/images/background.png
  src/assets/images/home.png
  src/common/Footer.tsx
  src/hook/useHomeQuery.ts
  src/hook/useLoginMutation.ts
  src/pages/home/Home.tsx
  src/pages/home/components/Banner.tsx
  src/pages/home/components/HomeDreamer.tsx
  src/pages/home/components/HomeImage.tsx
  src/pages/home/components/HomeRecruit.tsx
  src/pages/home/components/LoginBanner.tsx
  src/pages/home/components/tab/ReadyTab.tsx
  src/store/useUserStore.ts
  src/type/login/mutation.ts
Labels: ✨Feature, 💄Style

#89 [✨FEATURE] 직업탐색 API 연결
  src/assets/icons/purplelike.svg
  src/common/DropDown.tsx
  src/common/Pagination.tsx
  src/common/modal/SelectModal.tsx
  src/hook/useJobQuery.ts
  src/pages/home/components/Banner.tsx
  src/pages/home/components/LoginBanner.tsx
  src/pages/jobDetail/JobInfo.tsx
  src/pages/jobDetail/components/JobView.tsx
  src/pages/jobfound/JobFound.tsx
  src/pages/jobfound/components/FoundFilter.tsx
  src/pages/jobfound/components/ListFound.tsx
  src/route/Router.tsx
Labels: ✨Feature

#95 [✨FEATURE] 직업탐색 필터 적용
  src/hook/useJobQuery.ts
  src/pages/jobDetail/JobInfo.tsx
  src/pages/jobDetail/components/DetailSideBar.tsx
  src/pages/jobfound/JobFound.tsx
  src/pages/jobfound/components/ListFound.tsx
Labels: ✨Feature

#99 [✨FEATURE] 타유저 투두 페이지 UI
  src/assets/icons/delete-trash.svg
  src/assets/icons/edit-write.svg
  src/assets/icons/memo.svg
  src/common/Divider.tsx
  src/hook/useRecruitListQuery.ts
  src/pages/jobDetail/components/DetailSideBar.tsx
  src/pages/otherTodo/OtherTodoPage.tsx
  src/pages/otherTodo/components/ProfileCard.tsx
  src/pages/otherTodoList/OtherTodoListPage.tsx
  src/pages/otherTodoList/components/TodoCard.tsx
  src/route/Router.tsx
Labels: 🐛Bug, ✨Feature, 💄Style

#106 [✨FEATURE] 홈 새로 올라온 구인글 api 연결
  src/hook/useHomeQuery.ts
  src/pages/home/components/HomeRecruit.tsx
Labels: ✨Feature

#109 [✨FEATURE] QA 반영
  src/common/Header.tsx
  src/common/modal/AddJobModal.tsx
  src/common/modal/SelectModal.tsx
  src/common/modal/ToastModal.tsx
  src/hook/useJobQuery.ts
  src/pages/jobDetail/JobInfo.tsx
  src/pages/jobDetail/components/DetailSideBar.tsx
  src/pages/jobDetail/components/JobView.tsx
  src/pages/jobfound/components/ListFound.tsx
  src/pages/signup/components/AddressModal.tsx
Labels: 🐛Bug, ✨Feature

#117 [✨FEATURE] 2차 QA 반영
  src/common/modal/FloatingModal.tsx
  src/pages/home/components/Banner.tsx
  src/pages/jobDetail/components/DetailSideBar.tsx
Labels: ✨Feature, 💄Style

#122 [✨FEATURE] 사이드바 구현
  src/outlet/SidebarLayout.tsx
  src/pages/mydream/Mydream.tsx
  src/pages/mydream/TodoList.tsx
  src/route/Router.tsx
Labels: 💄Style

#139 [✨FEATURE] 채용정보 (구) 배움터 API 연결
  src/common/DropDown.tsx
  src/common/RecruitCard.tsx
  src/common/ResetButton.tsx
  src/hook/useAcademyInfoQuery.ts
  src/hook/useRecruitListQuery.ts
  src/pages/jobSearch/JobSearchPage.tsx
  src/pages/jobSearch/components/CardDetail.tsx
  src/pages/jobSearch/components/Filter.tsx
  src/pages/jobSearch/components/RecruitCard.tsx
  src/pages/learning/LearningPage.tsx
  src/pages/learning/components/CardDetail.tsx
  src/pages/learning/components/Filter.tsx
  src/pages/learning/components/LearningCard.tsx
  src/pages/myTodo/tabs/ScrapPage.tsx
  src/store/academyFilterStore.ts
  src/store/filterStore.ts
  src/utils/data/job/jobMapper.ts
  src/utils/functions/dateCompare.ts
  src/validation/academy/academySchema.ts
  src/validation/recruit/recruitSchema.ts
Labels: ✨Feature

#145 [✨FEATURE] 구) 배움터 정렬API 연결
  src/hook/useAcademyInfoQuery.ts
  src/pages/jobSearch/JobSearchPage.tsx
  src/pages/learning/LearningPage.tsx
  src/pages/learning/components/LearningCard.tsx
  src/pages/onboard/OnBoardingPage.tsx
  src/store/academyFilterStore.ts
  src/validation/recruit/recruitSchema.ts
Labels: ✨Feature

#148 [✨FEATURE] 마이드림 할일목록(D1-1) UI 구현
  src/common/CheckList.tsx
  src/common/FloatingButton.tsx
  src/common/Header.tsx
  src/common/modal/ToastModal.tsx
  src/outlet/SidebarLayout.tsx
  src/pages/jobDetail/components/ProfileCard.tsx
  src/pages/myTodo/components/todo/Todo.tsx
  src/pages/myTodo/tabs/TodoListPage.tsx
  src/route/Router.tsx
Labels: ✨Feature, 💄Style

#151 [✨FEATURE] 내계정 UI 구현
  src/assets/icons/camera.svg
  src/assets/icons/edit-nickname.svg
  src/assets/icons/profile_delete.svg
  src/assets/icons/warning.svg
  src/assets/images/profile.png
  src/assets/images/quitmodalimg.webp
  src/common/CheckList.tsx
  src/common/Header.tsx
  src/common/modal/LikeJobModal.tsx
  src/common/modal/PasswordChangeModal.tsx
  src/common/modal/Quit.tsx
  src/hook/useLogout.ts
  src/pages/home/components/DreamerCard.tsx
  src/pages/mypage/Mypage.tsx
  src/route/Router.tsx
Labels: ✨Feature, 💄Style

#154 [🐛BUG] 로그인 이후, 온보딩 체크
  src/hook/todo/useMdTodoQuery.ts
  src/hook/useLoginMutation.ts
  src/pages/home/components/LoginBanner.tsx
  src/pages/myTodo/components/todo/Todo.tsx
  src/pages/otherTodo/OtherTodoPage.tsx
  src/validation/mydream/todoSchema.ts
Labels: 🐛Bug, ✨Feature

#162 [✨FEATURE] 마이페이지 API 연결
  src/assets/icons/warning.svg
  src/common/Header.tsx
  src/common/modal/LikeJobModal.tsx
  src/common/modal/PasswordChangeModal.tsx
  src/common/modal/Quit.tsx
  src/hook/mypage/useEditNicknameMutation.ts
  src/hook/mypage/useMypageQuery.ts
  src/hook/mypage/useQuitMutation.ts
  src/hook/mypage/useRemoveJob.ts
  src/hook/mypage/useUpdatePassword.ts
  src/hook/mypage/useUpdateRegion.ts
  src/hook/mypage/useUploadImage.ts
  src/hook/useLoginMutation.ts
  src/hook/useLogout.ts
  src/pages/mypage/Mypage.tsx
  src/pages/mypage/components/Nickname.tsx
  src/pages/mypage/components/ProfileImageUploader.tsx
  src/pages/mypage/components/UpdateRegion.tsx
  src/store/useUserStore.ts
  src/validation/mypage/UpdatePasswordSchema.ts
Labels: ✨Feature

#166 [✨FEATURE] 홈화면 API 연결
  src/common/Header.tsx
  src/common/modal/AddJobModal.tsx
  src/hook/home/useDreamerQuery.ts
  src/hook/home/useNoLoginDreamerQuery.ts
  src/pages/home/components/DreamerCard.tsx
  src/pages/home/components/HomeDreamer.tsx
  src/pages/home/components/HomeRecruit.tsx
  src/pages/jobDetail/components/DetailSideBar.tsx
  src/pages/mypage/components/ProfileImageUploader.tsx
  src/store/useUserStore.ts
Labels: ✨Feature

#169 [✨FEATURE] 플로팅 모달 연결
  src/common/FloatingButton.tsx
  src/common/modal/FloatingModal.tsx
  src/hook/floating/FloatingAddJob.ts
  src/hook/floating/FloatingButtonMutation.ts
Labels: ✨Feature

#172 [✨FEATURE]스크랩 api 연결
  src/hook/mydream/useMdTodoCompleMutation.ts
  src/hook/scrap/recruit/useDeleteScrapRecruitMutation.ts
  src/hook/scrap/recruit/useScrapRecruitMutation.ts
  src/hook/scrap/recruit/useScrapRecruitQuery.ts
  src/hook/scrap/training/useDeleteScrapTrainingMutation.ts
  src/hook/scrap/training/useScrapTrainingMutation.ts
  src/hook/scrap/training/useScrapTrainingQuery.ts
  src/hook/scrap/useScrapCheckQuery.ts
  src/hook/todo/useTdJobsQuery.ts
  src/hook/todo/useTodoGroupQuery.ts
  src/hook/useAcademyInfoQuery.ts
  src/hook/useRecruitListQuery.ts
  src/pages/jobSearch/JobSearchPage.tsx
  src/pages/jobSearch/components/CardDetail.tsx
  src/pages/jobSearch/components/RecruitCard.tsx
  src/pages/learning/LearningPage.tsx
  src/pages/learning/components/CardDetail.tsx
  src/pages/learning/components/LearningCard.tsx
  src/pages/myTodo/components/scrap/CustomSortDropdown.tsx
  src/pages/myTodo/components/scrap/ScrapListSection.tsx
  src/pages/myTodo/components/scrap/ScrappedItemCard.tsx
  src/pages/myTodo/components/todo/Todo.tsx
  src/pages/myTodo/tabs/ScrapPage.tsx
  src/pages/onboard/OnBoardingPage.tsx
  src/route/Router.tsx
  src/validation/mydream/todoGroupSchema.ts
  src/validation/scrap/scrapCheckSchema.ts
  src/validation/scrap/scrapRecruitSchema.ts
  src/validation/scrap/scrapSchema.ts
Labels: ✨Feature

#175 [✨FEATURE] 타유저 투두리스트 메모 조회
  src/hook/mydream/useGetMemo.ts
  src/hook/useJobQuery.ts
  src/outlet/SidebarLayout.tsx
  src/pages/jobfound/components/ListFound.tsx
  src/pages/myTodo/components/todo/AutoTextArea.tsx
  src/pages/myTodo/components/todo/Container.tsx
  src/pages/myTodo/components/todo/MyEditor.tsx
  src/pages/myTodo/tabs/TodoListPage.tsx
  src/pages/otherTodoList/components/TodoCard.tsx
  src/route/Router.tsx
  src/utils/preview/LinkEditor.tsx
Labels: ✨Feature

#179 [🐛BUG] QA 수정사항
  src/common/modal/FloatingModal.tsx
  src/hook/mypage/useDeleteProfile.tsx
  src/pages/home/Home.tsx
  src/pages/home/components/HomeDreamer.tsx
  src/pages/home/components/LoginBanner.tsx
  src/pages/jobDetail/JobInfo.tsx
  src/pages/jobDetail/components/ProfileCard.tsx
  src/pages/jobfound/components/FoundFilter.tsx
  src/pages/myTodo/components/todo/Todo.tsx
  src/pages/mypage/components/ProfileImageUploader.tsx
  src/pages/signup/components/AddressModal.tsx
  src/pages/signup/components/Signup2.tsx
  src/route/Router.tsx
  src/utils/RequireLogin.tsx
Labels: 🐛Bug

#210 [✨FEATURE] ReadMe 업데이트
  README.md
Labels: 📄Docs

#216 [🐛BUG] 직업상세 직업목록 보러가기 수정
  src/common/modal/AddJobModal.tsx
  src/pages/jobRecommend/JobRecommendPage.tsx
Labels: 🐛Bug
